"""
Data preprocessing, metadata generation, analytics, and logging.

Srikanth's Module:
- Data preprocessing & validation
- Metadata generation for documents
- Analytics and dataset statistics
- Document information storage (in-memory registry)
- Structured logging integration
"""

import hashlib
import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from app.core.config import settings
from app.core.logger import get_logger

logger = get_logger(__name__)


class AnalyticsService:
    """
    Handles metadata generation, document registry, dataset analytics,
    and preprocessing validation for the OmniBrain system.
    """

    def __init__(self) -> None:
        """Initialize the in-memory document registry and analytics store."""
        self._documents: dict[str, dict[str, Any]] = {}
        self._start_time: float = time.time()
        logger.info("AnalyticsService initialized")

    # ── Metadata Generation ──────────────────────────────────────────

    def generate_metadata(
        self,
        document_id: str,
        filename: str,
        file_size_bytes: int,
        pdf_metadata: dict[str, Any],
        pages: list[dict[str, Any]],
        chunks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """
        Generate comprehensive metadata for a processed document.

        Args:
            document_id: Unique document identifier.
            filename: Original filename.
            file_size_bytes: File size on disk.
            pdf_metadata: Metadata from the PDF (title, author, etc.).
            pages: Preprocessed page data.
            chunks: Chunk data from the chunking pipeline.

        Returns:
            A metadata dictionary with document-level statistics.
        """
        total_chars = sum(p["char_count"] for p in pages)
        total_cleaned_chars = sum(len(p["cleaned_text"]) for p in pages)

        # Chunk statistics
        chunk_lengths = [c["char_count"] for c in chunks] if chunks else [0]

        metadata: dict[str, Any] = {
            "document_id": document_id,
            "filename": filename,
            "file_size_bytes": file_size_bytes,
            "file_size_mb": round(file_size_bytes / (1024 * 1024), 2),
            "created_at": datetime.now(timezone.utc).isoformat(),
            "pdf_title": pdf_metadata.get("title", ""),
            "pdf_author": pdf_metadata.get("author", ""),
            "total_pages": len(pages),
            "total_chunks": len(chunks),
            "total_characters_raw": total_chars,
            "total_characters_cleaned": total_cleaned_chars,
            "avg_chunk_size": round(np.mean(chunk_lengths), 1) if chunk_lengths else 0,
            "min_chunk_size": int(np.min(chunk_lengths)) if chunk_lengths else 0,
            "max_chunk_size": int(np.max(chunk_lengths)) if chunk_lengths else 0,
            "std_chunk_size": round(float(np.std(chunk_lengths)), 1) if len(chunk_lengths) > 1 else 0.0,
            "file_hash": self._compute_file_hash(filename, document_id),
            "status": "indexed",
        }
        return metadata

    def _compute_file_hash(self, filename: str, document_id: str) -> str:
        """Compute a simple content hash from filename + ID."""
        raw = f"{filename}:{document_id}:{time.time()}"
        return hashlib.sha256(raw.encode()).hexdigest()[:16]

    # ── Document Registry ────────────────────────────────────────────

    def register_document(self, document_id: str, metadata: dict[str, Any]) -> None:
        """
        Register a document's metadata in the in-memory registry.

        Args:
            document_id: Unique document identifier.
            metadata: The metadata dict generated by generate_metadata().
        """
        self._documents[document_id] = metadata
        logger.info(f"Document registered: {document_id} ({metadata.get('filename')})")

        # Also persist to reports directory as JSON
        self._persist_metadata(document_id, metadata)

    def get_document(self, document_id: str) -> Optional[dict[str, Any]]:
        """Retrieve metadata for a specific document."""
        return self._documents.get(document_id)

    def get_all_documents(self) -> list[dict[str, Any]]:
        """Return metadata for all registered documents, newest first."""
        docs = list(self._documents.values())
        docs.sort(key=lambda d: d.get("created_at", ""), reverse=True)
        return docs

    def remove_document(self, document_id: str) -> bool:
        """
        Remove a document from the registry.

        Args:
            document_id: Document to remove.

        Returns:
            True if removed, False if not found.
        """
        if document_id in self._documents:
            del self._documents[document_id]
            logger.info(f"Document removed from registry: {document_id}")
            return True
        logger.warning(f"Document not found in registry: {document_id}")
        return False

    def _persist_metadata(self, document_id: str, metadata: dict[str, Any]) -> None:
        """Save metadata JSON to the reports directory."""
        try:
            reports_dir = Path(settings.REPORTS_DIR)
            reports_dir.mkdir(parents=True, exist_ok=True)
            file_path = reports_dir / f"{document_id}.json"
            with open(file_path, "w") as f:
                json.dump(metadata, f, indent=2, default=str)
        except Exception as exc:
            logger.error(f"Failed to persist metadata for {document_id}: {exc}")

    # ── Analytics ────────────────────────────────────────────────────

    def compute_dataset_statistics(self) -> dict[str, Any]:
        """
        Compute aggregate statistics across all indexed documents.

        Returns:
            A dict with overall dataset analytics.
        """
        docs = list(self._documents.values())
        if not docs:
            return {
                "total_documents": 0,
                "total_chunks": 0,
                "total_pages": 0,
                "total_characters": 0,
                "avg_pages_per_doc": 0.0,
                "avg_chunks_per_doc": 0.0,
                "avg_chunk_size": 0.0,
            }

        df = pd.DataFrame(docs)
        stats: dict[str, Any] = {
            "total_documents": int(df.shape[0]),
            "total_chunks": int(df["total_chunks"].sum()),
            "total_pages": int(df["total_pages"].sum()),
            "total_characters": int(df["total_characters_cleaned"].sum()),
            "avg_pages_per_doc": round(float(df["total_pages"].mean()), 1),
            "avg_chunks_per_doc": round(float(df["total_chunks"].mean()), 1),
            "avg_chunk_size": round(float(df["avg_chunk_size"].mean()), 1),
            "total_file_size_mb": round(float(df["file_size_mb"].sum()), 2),
            "unique_authors": int(df["pdf_author"].nunique()) if "pdf_author" in df else 0,
        }
        return stats

    def compute_document_similarity(
        self, document_ids: Optional[list[str]] = None
    ) -> dict[str, Any]:
        """
        Compute pairwise TF-IDF cosine similarity between documents.

        Args:
            document_ids: Optional subset of document IDs. All if None.

        Returns:
            Dict with a similarity matrix keyed by document IDs.
        """
        docs = self.get_all_documents()
        if document_ids:
            docs = [d for d in docs if d["document_id"] in document_ids]

        if len(docs) < 2:
            return {"similarity_matrix": {}, "message": "Need at least 2 documents for comparison"}

        # Use filenames as proxy text (in production, use document summaries)
        corpus = [d["filename"] for d in docs]
        doc_ids = [d["document_id"] for d in docs]

        vectorizer = TfidfVectorizer(stop_words="english")
        tfidf_matrix = vectorizer.fit_transform(corpus)
        sim_matrix = cosine_similarity(tfidf_matrix)

        result: dict[str, Any] = {}
        for i, doc_id_i in enumerate(doc_ids):
            result[doc_id_i] = {}
            for j, doc_id_j in enumerate(doc_ids):
                if i != j:
                    result[doc_id_i][doc_id_j] = round(float(sim_matrix[i][j]), 4)

        return {"similarity_matrix": result, "documents_compared": len(docs)}

    def get_document_report(self, document_id: str) -> Optional[dict[str, Any]]:
        """
        Get a detailed analytics report for a specific document.

        Args:
            document_id: Document ID to report on.

        Returns:
            Report dict or None if not found.
        """
        doc = self.get_document(document_id)
        if not doc:
            return None

        return {
            "document_id": doc["document_id"],
            "filename": doc["filename"],
            "size_mb": doc["file_size_mb"],
            "pages": doc["total_pages"],
            "chunks": doc["total_chunks"],
            "characters_raw": doc["total_characters_raw"],
            "characters_cleaned": doc["total_characters_cleaned"],
            "compression_ratio": round(
                doc["total_characters_cleaned"] / max(doc["total_characters_raw"], 1), 4
            ),
            "chunk_size_stats": {
                "avg": doc["avg_chunk_size"],
                "min": doc["min_chunk_size"],
                "max": doc["max_chunk_size"],
                "std": doc["std_chunk_size"],
            },
            "created_at": doc["created_at"],
        }

    # ── Preprocessing Validation ─────────────────────────────────────

    def validate_chunks(self, chunks: list[dict[str, Any]]) -> list[str]:
        """
        Validate chunk data and return a list of warnings.

        Checks:
            - Non-empty text
            - Minimum length
            - Contains page numbers

        Args:
            chunks: Chunks from the PDF service chunking pipeline.

        Returns:
            List of warning messages (empty if all valid).
        """
        warnings: list[str] = []
        for chunk in chunks:
            text = chunk.get("text", "").strip()
            if not text:
                warnings.append(f"Chunk {chunk.get('chunk_index')} is empty")
            elif len(text) < 10:
                warnings.append(f"Chunk {chunk.get('chunk_index')} is too short ({len(text)} chars)")
            if not chunk.get("page_numbers"):
                warnings.append(f"Chunk {chunk.get('chunk_index')} has no page numbers")

        if warnings:
            logger.warning(f"Chunk validation: {len(warnings)} warnings")
        else:
            logger.info("All chunks passed validation")
        return warnings

    # ── Utility ──────────────────────────────────────────────────────

    def get_uptime_seconds(self) -> float:
        """Return server uptime in seconds."""
        return time.time() - self._start_time